apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-spark-role
  namespace: spark
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["sparkoperator.k8s.io"]
    resources: ["sparkapplications","sparkapplications/status"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
